name: Auto Test

env:
  total_coverage: 75
  coverage_per_file: 50

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm run test:inula-jest | tee ./coverage.txt && exit ${PIPESTATUS[0]}

      - name: Jest Coverage Comment
        id: jest_coverage_comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-path: ./coverage.txt

      - name: Check Total Coverage
        run: |
          if [ ${{ steps.jest_coverage_comment.outputs.coverage }} -lt ${{ env.total_coverage }} ]; then
            echo "Coverage is less than 75%. Failing the workflow."
            exit 1
          fi

      - name: Check Coverage Per File
        run: |
          html_content="${{ steps.jest_coverage_comment.outputs.coverageHtml }}"
          matches=$(echo "$html_content" | grep -o '<td>[1-9][0-9]*\(\.[0-9]*\)\{0,1\}</td>' | sed 's/<td>\(.*\)<\/td>/\1/g')
          while read -r match; do
            result=$(awk -v num="$match" 'BEGIN {if (num < ${{ env.coverage_per_file }}) print "fail"; else print "pass"}')
            echo "Number: $match Result: $result"
            if [ "$result" == "fail" ]; then
              echo "Workflow failed!"
              exit 1
            fi
          done <<< "$matches"
